import math

# This may be generated by a program.
weights = {}

class classifier:
    """ linear classifier (binary) """

    def __init__(self, model=None):
        if model is not None:
            self.weights = model.weights    # External model.
        else:
            self.weights = weights          # Build-in model.
        self.clear()

    def clear(self):
        self.score = self.weights.get('__BIAS__', 0.)

    def add(self, a, v):
        self.score += self.weights.get(a, 0.) * v

    def set(self, inst):
        self.clear()
        for a, v in inst:
            self.set(a, v)

    def label(self):
        return (0. < self.score)

    def score(self):
        return self.score

    def prob(self):
        if -100. < self.score:
            return (1. / (1. + math.exp(-self.score)))
        else:
            return 0.

